name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM with ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          pdm install
          pdm run pytest -vv
